-- Creating seed data for the burgers_db database --
-- INSERT INTO RealWize_DB (schools) VALUES ('<<<INFO FROM ATTOM>>>', true);
-- INSERT INTO RealWize_DB (schools) VALUES ('<<<INFO FROM ATTOM>>>', true);
-- INSERT INTO RealWize_DB (price) VALUES ('<<<INFO FROM ATTOM>>>', true);
-- INSERT INTO RealWize_DB (last_price) VALUES ('<<<INFO FROM ATTOM>>>', true);
-- INSERT INTO RealWize_DB (lot_size) VALUES ('<<<INFO FROM ATTOM>>>', true);
-- INSERT INTO RealWize_DB (neighborhood) VALUES ('<<<INFO FROM ATTOM>>>', true);
-- INSERT INTO RealWize_DB (date_listed) VALUES ('<<<INFO FROM ATTOM>>>', true);
-- INSERT INTO RealWize_DB (rooms_amenities) VALUES ('<<<INFO FROM ATTOM>>>', true);